### PR TITLE
removed resty from the dockerfile

### PR DESCRIPTION
**Pull request by thoraxe**
Stopped using resty because of tty issues and switched to httpie, but forgot to remove resty from the dockerfile.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@thoraxe the job is running now, as expected. Do you want us to refresh the image that we use to run it based on changes in the PR? Like in this PR -- I had to manually re-kick the image since you change it in the PR itself.

**Comment by thoraxe** [comment]
@stevekuznetsov This latest PR commit includes removing the -x which you requested. So you would need to refresh the image with this PR in order to get the -x out.

**Pull request merged**
