### PR TITLE
oc volume is deprecated the command has been moved to "oc set volume"

### PR DESCRIPTION
**Pull request by paddy667**
Updating the lab guides to replace `oc volume` with `oc set volume`

While I was working through the labs I received the following everytime I ran `oc volume`

`DEPRECATED: This command has been moved to "oc set volume"`

### CODE REVIEW

**Comment by cooktheryan** [comment]
Using 3.10.34-1 i didn't get this error. @thoraxe both ways appear to work

The GA docs have oc volume https://docs.openshift.com/container-platform/3.10/dev_guide/volumes.html#adding-volumes

**Comment by paddy667** [comment]
In labs I was using 3.9. So maybe this resolves itself after the cluster is upgraded?

**Comment by thoraxe** [comment]
@cooktheryan i do see the wrning in the 3.10 environment:

```
[root@master tests]# oc volume -h
DEPRECATED: This command has been moved to "oc set volume"
```

It's not fatal which is likely why nothing is picking it up.

@paddy667 can you also add to your PR changes to the `tests` / Ansible files so that we can run your changes through CI?

**Comment by paddy667** [comment]
@thoraxe done. Let me know if you need anything else.

**Comment by thoraxe** [comment]
@paddy667 LGTM. Thanks for your contribution.

**Pull request merged**
