### PR TITLE
Prometheus

### PR DESCRIPTION
**Pull request by cooktheryan**

### CODE REVIEW

**Comment by thoraxe** [comment]
I'm fine with merging this. Prometheus works and is there. It has no dashboards or anything, but it's good enough to merge now I think.

@cooktheryan are you planning to write the "tests" to verify that prometheus is installed and minimally working?

**Comment by cooktheryan** [comment]
@thoraxe was going to take it in baby steps just in case I got pulled away. Ill probably start working on the testing tomorrow

**Comment by thoraxe** [comment]
@cooktheryan SGTM. Will you add that to this PR or to its own PR?

**Comment by cooktheryan** [comment]
@thoraxe let's make the testing a separate PR

**Comment by thoraxe** [comment]
@dmesser I'm fine to merge this. You?

**Pull request merged**
